from .aviso_views import (
    aviso_create_view,
    aviso_delete_view,
    aviso_detail_view,
    aviso_grupos_options_view,
    aviso_home_view,
    aviso_list_view,
    aviso_update_view,
)
from .condominio_views import (
    condominio_create_view,
    condominio_delete_view,
    condominio_detail_view,
    condominio_list_view,
    condominio_logo_db_view,
    condominio_options_view,
    condominio_update_view,
    condominio_upload_logo_db_view,
)
from .dashboard_views import morador_stats_view, sindico_stats_view
from .encomenda_views import (
    encomenda_badge_view,
    encomenda_create_view,
    encomenda_delete_view,
    encomenda_detail_view,
    encomenda_list_view,
    encomenda_update_view,
)
from .espaco_views import (
    espaco_create_view,
    espaco_delete_view,
    espaco_detail_view,
    espaco_disponibilidade_view,
    espaco_inventario_create_view,
    espaco_inventario_delete_view,
    espaco_inventario_detail_view,
    espaco_inventario_list_view,
    espaco_inventario_update_view,
    espaco_list_view,
    espaco_reserva_create_view,
    espaco_reserva_delete_view,
    espaco_reserva_detail_view,
    espaco_reserva_hoje_view,
    espaco_reserva_list_view,
    espaco_reserva_update_view,
    espaco_update_view,
)
from .evento_views import (
    evento_create_view,
    evento_delete_view,
    evento_detail_view,
    evento_imagem_db_view,
    evento_list_view,
    evento_update_view,
)
from .unidade_views import (
    unidade_create_bulk_view,
    unidade_create_view,
    unidade_delete_view,
    unidade_detail_view,
    unidade_inactivate_view,
    unidade_list_view,
    unidade_update_view,
)
from .veiculo_views import (
    veiculo_create_view,
    veiculo_delete_view,
    veiculo_detail_view,
    veiculo_list_view,
    veiculo_update_view,
)
from .visitante_views import (
    visitante_create_view,
    visitante_delete_view,
    visitante_detail_view,
    visitante_list_view,
    visitante_update_view,
)

__all__ = [
    "condominio_list_view",
    "condominio_create_view",
    "condominio_detail_view",
    "condominio_update_view",
    "condominio_delete_view",
    "condominio_options_view",
    "condominio_logo_db_view",
    "condominio_upload_logo_db_view",
    "encomenda_list_view",
    "encomenda_create_view",
    "encomenda_detail_view",
    "encomenda_update_view",
    "encomenda_delete_view",
    "encomenda_badge_view",
    # Espaços
    "espaco_list_view",
    "espaco_create_view",
    "espaco_detail_view",
    "espaco_update_view",
    "espaco_delete_view",
    # Inventário de Espaços
    "espaco_inventario_list_view",
    "espaco_inventario_create_view",
    "espaco_inventario_detail_view",
    "espaco_inventario_update_view",
    "espaco_inventario_delete_view",
    # Reservas de Espaços
    "espaco_reserva_list_view",
    "espaco_reserva_create_view",
    "espaco_reserva_detail_view",
    "espaco_reserva_update_view",
    "espaco_reserva_delete_view",
    "espaco_reserva_hoje_view",
    "espaco_disponibilidade_view",
    "unidade_list_view",
    "unidade_create_view",
    "unidade_create_bulk_view",
    "unidade_detail_view",
    "unidade_update_view",
    "unidade_inactivate_view",
    "unidade_delete_view",
    "veiculo_list_view",
    "veiculo_create_view",
    "veiculo_detail_view",
    "veiculo_update_view",
    "veiculo_delete_view",
    "visitante_list_view",
    "visitante_create_view",
    "visitante_detail_view",
    "visitante_update_view",
    "visitante_delete_view",
    "aviso_list_view",
    "aviso_create_view",
    "aviso_detail_view",
    "aviso_update_view",
    "aviso_delete_view",
    "aviso_grupos_options_view",
    "aviso_home_view",
    "morador_stats_view",
    "sindico_stats_view",
    # Eventos
    "evento_list_view",
    "evento_create_view",
    "evento_detail_view",
    "evento_imagem_db_view",
    "evento_update_view",
    "evento_delete_view",
]
