# Generated by Django 4.2.10 on 2025-10-09 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Condominio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome completo do condomínio",
                        max_length=255,
                        verbose_name="Nome do Condomínio",
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(
                        help_text="CNPJ no formato XX.XXX.XXX/XXXX-XX",
                        max_length=18,
                        unique=True,
                        verbose_name="CNPJ",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        help_text="Telefone de contato do condomínio",
                        max_length=15,
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "endereco",
                    models.TextField(
                        help_text="Endereço completo do condomínio",
                        verbose_name="Endereço",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo do condomínio",
                        null=True,
                        upload_to="condominios/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Condomínio",
                "verbose_name_plural": "Condomínios",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Visitante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome completo do visitante",
                        max_length=255,
                        verbose_name="Nome do Visitante",
                    ),
                ),
                (
                    "documento",
                    models.CharField(
                        help_text="CPF, RG ou outro documento de identificação",
                        max_length=20,
                        verbose_name="Documento",
                    ),
                ),
                (
                    "data_entrada",
                    models.DateTimeField(
                        help_text="Data e hora de entrada do visitante",
                        verbose_name="Data de Entrada",
                    ),
                ),
                (
                    "data_saida",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora de saída do visitante",
                        null=True,
                        verbose_name="Data de Saída",
                    ),
                ),
                (
                    "is_permanente",
                    models.BooleanField(
                        default=False,
                        help_text="Marque se o visitante tem acesso permanente",
                        verbose_name="Visitante Permanente",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "morador",
                    models.ForeignKey(
                        help_text="Morador que está recebendo o visitante",
                        limit_choices_to={"groups__name": "Moradores"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitantes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Morador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visitante",
                "verbose_name_plural": "Visitantes",
                "ordering": ["-data_entrada"],
            },
        ),
        migrations.CreateModel(
            name="Encomenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        help_text="Descrição da encomenda", verbose_name="Descrição"
                    ),
                ),
                (
                    "codigo_rastreio",
                    models.CharField(
                        blank=True,
                        help_text="Código de rastreamento da encomenda",
                        max_length=100,
                        null=True,
                        verbose_name="Código de Rastreio",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "retirado_por",
                    models.CharField(
                        blank=True,
                        help_text="Nome da pessoa que retirou a encomenda",
                        max_length=255,
                        null=True,
                        verbose_name="Retirado por",
                    ),
                ),
                (
                    "retirado_em",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora em que a encomenda foi retirada",
                        null=True,
                        verbose_name="Retirado em",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encomendas_criadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "destinatario",
                    models.ForeignKey(
                        help_text="Morador que receberá a encomenda",
                        limit_choices_to={"groups__name": "Moradores"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encomendas_recebidas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinatário",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encomendas_atualizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Encomenda",
                "verbose_name_plural": "Encomendas",
                "ordering": ["-created_on"],
            },
        ),
    ]
