# Generated by Django 4.2.10 on 2026-03-31 22:24

import cadastros.models.veiculo
import cadastros.models.visitante
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Condominio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome completo do condomínio",
                        max_length=255,
                        verbose_name="Nome do Condomínio",
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(
                        help_text="CNPJ no formato XX.XXX.XXX/XXXX-XX",
                        max_length=18,
                        unique=True,
                        verbose_name="CNPJ",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        help_text="Telefone de contato do condomínio",
                        max_length=15,
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "cep",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="CEP do condomínio (somente números)",
                        max_length=8,
                        verbose_name="CEP",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Número do endereço",
                        max_length=10,
                        verbose_name="Número",
                    ),
                ),
                (
                    "complemento",
                    models.CharField(
                        blank=True,
                        help_text="Complemento do endereço (opcional)",
                        max_length=100,
                        null=True,
                        verbose_name="Complemento",
                    ),
                ),
                (
                    "signup_slug",
                    models.SlugField(
                        blank=True,
                        help_text="Slug único usado no link de cadastro de moradores",
                        max_length=120,
                        null=True,
                        unique=True,
                        verbose_name="Slug de cadastro",
                    ),
                ),
                (
                    "signup_token",
                    models.CharField(
                        blank=True,
                        help_text="Token secreto para validar o link de cadastro de moradores",
                        max_length=64,
                        null=True,
                        verbose_name="Token de cadastro",
                    ),
                ),
                (
                    "logo",
                    models.FileField(
                        blank=True,
                        help_text="Logo do condomínio (png, jpg, jpeg, svg — qualquer tamanho)",
                        null=True,
                        upload_to="condominios/logos/",
                    ),
                ),
                (
                    "logo_db_data",
                    models.BinaryField(
                        blank=True,
                        help_text="Dados binários da logo (se armazenada no DB)",
                        null=True,
                    ),
                ),
                (
                    "logo_db_content_type",
                    models.CharField(
                        blank=True,
                        help_text="Content-Type do arquivo",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "logo_db_filename",
                    models.CharField(
                        blank=True,
                        help_text="Nome original do arquivo",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "is_ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o condomínio está ativo",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Condomínio",
                "verbose_name_plural": "Condomínios",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Espaco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("capacidade_pessoas", models.PositiveIntegerField(default=0)),
                (
                    "valor_aluguel",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Valor cobrado pela reserva do espaço por dia",
                        max_digits=10,
                        verbose_name="Valor do Aluguel",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="espacos_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="espacos_atualizados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Espaço",
                "verbose_name_plural": "Espaços",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Visitante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome completo do visitante",
                        max_length=255,
                        verbose_name="Nome do Visitante",
                    ),
                ),
                (
                    "documento",
                    models.CharField(
                        help_text="CPF, RG ou outro documento de identificação",
                        max_length=20,
                        verbose_name="Documento",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="E-mail do visitante para envio do QR Code (opcional)",
                        max_length=254,
                        null=True,
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "qr_token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Token único utilizado para geração do QR Code de entrada",
                        unique=True,
                        verbose_name="Token QR",
                    ),
                ),
                (
                    "placa_veiculo",
                    models.CharField(
                        blank=True,
                        help_text="Placa do veículo do visitante (opcional, formato ABC-1234 ou ABC1D23)",
                        max_length=8,
                        null=True,
                        validators=[
                            cadastros.models.visitante.validate_placa_brasileira
                        ],
                        verbose_name="Placa do Veículo",
                    ),
                ),
                (
                    "data_entrada",
                    models.DateTimeField(
                        help_text="Data e hora de entrada do visitante",
                        verbose_name="Data de Entrada",
                    ),
                ),
                (
                    "data_saida",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora de saída do visitante",
                        null=True,
                        verbose_name="Data de Saída",
                    ),
                ),
                (
                    "is_permanente",
                    models.BooleanField(
                        default=False,
                        help_text="Marque se o visitante tem acesso permanente",
                        verbose_name="Visitante Permanente",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "morador",
                    models.ForeignKey(
                        help_text="Morador que está recebendo o visitante",
                        limit_choices_to={"groups__name": "Moradores"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitantes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Morador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visitante",
                "verbose_name_plural": "Visitantes",
                "ordering": ["-data_entrada"],
            },
        ),
        migrations.CreateModel(
            name="Unidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        help_text="Número ou identificação da unidade (ex: 101, 201A, etc.)",
                        max_length=20,
                        verbose_name="Número da Unidade",
                    ),
                ),
                (
                    "bloco",
                    models.CharField(
                        blank=True,
                        help_text="Bloco ou torre onde a unidade está localizada",
                        max_length=20,
                        null=True,
                        verbose_name="Bloco",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se a unidade está ativa no sistema",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unidades_criadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unidades_atualizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidade",
                "verbose_name_plural": "Unidades",
                "ordering": ["bloco", "numero"],
            },
        ),
        migrations.CreateModel(
            name="Ocorrencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("problema", "Problema"), ("sugestao", "Sugestão")],
                        max_length=10,
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberta", "Aberta"),
                            ("em_andamento", "Em Andamento"),
                            ("resolvida", "Resolvida"),
                            ("fechada", "Fechada"),
                        ],
                        default="aberta",
                        max_length=20,
                    ),
                ),
                ("resposta", models.TextField(blank=True, null=True)),
                ("respondido_em", models.DateTimeField(blank=True, null=True)),
                ("motivo_reabertura", models.TextField(blank=True, null=True)),
                ("reaberto_em", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocorrencias_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reaberto_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ocorrencias_reabertas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "respondido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ocorrencias_respondidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ocorrência",
                "verbose_name_plural": "Ocorrências",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ListaConvidados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255, verbose_name="Título")),
                (
                    "descricao",
                    models.TextField(blank=True, default="", verbose_name="Descrição"),
                ),
                (
                    "data_evento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Evento"
                    ),
                ),
                ("ativa", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "local_tipo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("espaco", "Espaço do Condomínio"),
                            ("unidade", "Unidade do Morador"),
                        ],
                        default="",
                        max_length=10,
                        verbose_name="Tipo de Local do Evento",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "espaco",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listas_convidados",
                        to="cadastros.espaco",
                        verbose_name="Espaço do Evento",
                    ),
                ),
                (
                    "morador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listas_convidados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Morador",
                    ),
                ),
                (
                    "unidade_evento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listas_convidados_evento",
                        to="cadastros.unidade",
                        verbose_name="Unidade do Evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lista de Convidados",
                "verbose_name_plural": "Listas de Convidados",
            },
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Título do evento",
                        max_length=255,
                        verbose_name="Título",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        help_text="Descrição detalhada do evento",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "local_texto",
                    models.CharField(
                        blank=True,
                        help_text="Descrição do local quando não for um espaço cadastrado",
                        max_length=255,
                        null=True,
                        verbose_name="Local (texto)",
                    ),
                ),
                (
                    "datetime_inicio",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora de início do evento",
                        null=True,
                        verbose_name="Início",
                    ),
                ),
                (
                    "datetime_fim",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora de término do evento",
                        null=True,
                        verbose_name="Término",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        help_text="Imagem ilustrativa do evento (legado — prefer imagem_db)",
                        null=True,
                        upload_to="eventos/",
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "imagem_db_data",
                    models.BinaryField(
                        blank=True,
                        help_text="Dados binários da imagem armazenados no banco",
                        null=True,
                    ),
                ),
                (
                    "imagem_db_content_type",
                    models.CharField(
                        blank=True,
                        help_text="Content-Type do arquivo de imagem",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "imagem_db_filename",
                    models.CharField(
                        blank=True,
                        help_text="Nome original do arquivo de imagem",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "espaco",
                    models.ForeignKey(
                        blank=True,
                        help_text="Espaço onde o evento acontecerá (opcional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos",
                        to="cadastros.espaco",
                        verbose_name="Espaço",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_atualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
            },
        ),
        migrations.CreateModel(
            name="Encomenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destinatario_nome",
                    models.CharField(
                        blank=True,
                        help_text="Nome da pessoa que receberá a encomenda",
                        max_length=255,
                        null=True,
                        verbose_name="Nome do Destinatário",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        help_text="Descrição da encomenda", verbose_name="Descrição"
                    ),
                ),
                (
                    "codigo_rastreio",
                    models.CharField(
                        blank=True,
                        help_text="Código de rastreamento da encomenda",
                        max_length=100,
                        null=True,
                        verbose_name="Código de Rastreio",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "retirado_por",
                    models.CharField(
                        blank=True,
                        help_text="Nome da pessoa que retirou a encomenda",
                        max_length=255,
                        null=True,
                        verbose_name="Retirado por",
                    ),
                ),
                (
                    "retirado_em",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora em que a encomenda foi retirada",
                        null=True,
                        verbose_name="Retirado em",
                    ),
                ),
                (
                    "contestacao_observacao",
                    models.TextField(
                        blank=True,
                        help_text="Observação do morador ao contestar o recebimento",
                        null=True,
                        verbose_name="Observação da Contestação",
                    ),
                ),
                (
                    "contestado_em",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora da contestação de recebimento",
                        null=True,
                        verbose_name="Contestado em",
                    ),
                ),
                (
                    "contestacao_resolvida",
                    models.BooleanField(
                        default=False, verbose_name="Contestação resolvida"
                    ),
                ),
                (
                    "contestacao_resposta",
                    models.TextField(
                        blank=True,
                        help_text="Resposta do síndico para o morador sobre a contestação",
                        null=True,
                        verbose_name="Resposta da Contestação",
                    ),
                ),
                (
                    "contestacao_respondido_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Contestação respondida em"
                    ),
                ),
                (
                    "contestacao_respondido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encomendas_contestacoes_respondidas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Contestação respondida por",
                    ),
                ),
                (
                    "contestado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encomendas_contestadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Contestado por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encomendas_criadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        blank=True,
                        help_text="Unidade destinatária da encomenda",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encomendas",
                        to="cadastros.unidade",
                        verbose_name="Unidade",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encomendas_atualizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Encomenda",
                "verbose_name_plural": "Encomendas",
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="CondominioLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.BinaryField(blank=True, null=True)),
                (
                    "content_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("filename", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "condominio",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logo_db",
                        to="cadastros.condominio",
                        verbose_name="Condomínio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Logo do Condomínio (DB)",
                "verbose_name_plural": "Logos de Condomínios (DB)",
            },
        ),
        migrations.CreateModel(
            name="Aviso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Média"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="media",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("ativo", "Ativo"),
                            ("inativo", "Inativo"),
                        ],
                        default="ativo",
                        max_length=10,
                    ),
                ),
                ("data_inicio", models.DateTimeField()),
                ("data_fim", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="avisos_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        blank=True,
                        help_text="(Legado) grupo principal de usuários que verá este aviso",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="avisos",
                        to="auth.group",
                    ),
                ),
                (
                    "grupos",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Grupos de usuários que verão este aviso",
                        related_name="avisos_destino",
                        to="auth.group",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="avisos_atualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Aviso",
                "verbose_name_plural": "Avisos",
                "ordering": ["-prioridade", "-data_inicio", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "placa",
                    models.CharField(
                        help_text="Placa do veículo (formato ABC-1234 ou ABC1D23)",
                        max_length=8,
                        validators=[cadastros.models.veiculo.validate_placa_brasileira],
                        verbose_name="Placa",
                    ),
                ),
                (
                    "marca_modelo",
                    models.CharField(
                        help_text="Marca e modelo do veículo (ex: Toyota Corolla)",
                        max_length=100,
                        verbose_name="Marca e Modelo",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o veículo está ativo no sistema",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="veiculos_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "morador",
                    models.ForeignKey(
                        help_text="Morador proprietário do veículo",
                        limit_choices_to=models.Q(
                            ("groups__name__iexact", "Moradores"),
                            ("groups__name__iexact", "Síndicos"),
                            ("groups__name__iexact", "Sindicos"),
                            _connector="OR",
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="veiculos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Morador",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="veiculos_atualizados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veículo",
                "verbose_name_plural": "Veículos",
                "ordering": ["-created_on"],
                "unique_together": {("placa", "morador")},
            },
        ),
        migrations.CreateModel(
            name="EspacoReserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_reserva",
                    models.DateField(
                        help_text="Data do dia reservado (dia completo)",
                        verbose_name="Data da Reserva",
                    ),
                ),
                (
                    "valor_cobrado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Valor que será cobrado pela reserva",
                        max_digits=10,
                        verbose_name="Valor Cobrado",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("confirmada", "Confirmada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="confirmada",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservas_criadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "espaco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="cadastros.espaco",
                        verbose_name="Espaço",
                    ),
                ),
                (
                    "morador",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            ("groups__name__iexact", "Moradores"),
                            ("groups__name__iexact", "Síndicos"),
                            ("groups__name__iexact", "Sindicos"),
                            _connector="OR",
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas_espacos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Morador",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservas_atualizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva de Espaço",
                "verbose_name_plural": "Reservas de Espaço",
                "ordering": ["-data_reserva"],
                "unique_together": {("espaco", "data_reserva")},
            },
        ),
        migrations.CreateModel(
            name="EspacoInventarioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("codigo", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="espaco_itens_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "espaco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventario_itens",
                        to="cadastros.espaco",
                        verbose_name="Espaço",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="espaco_itens_atualizados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Inventário do Espaço",
                "verbose_name_plural": "Itens de Inventário dos Espaços",
                "ordering": ["espaco__nome", "nome"],
                "unique_together": {("espaco", "codigo")},
            },
        ),
        migrations.CreateModel(
            name="ConvidadoLista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf", models.CharField(max_length=11, verbose_name="CPF")),
                ("nome", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="E-mail do Convidado",
                    ),
                ),
                (
                    "qr_token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Token QR Code",
                    ),
                ),
                (
                    "entrada_confirmada",
                    models.BooleanField(
                        default=False, verbose_name="Entrada Confirmada"
                    ),
                ),
                (
                    "entrada_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data/Hora da Entrada"
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "lista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="convidados",
                        to="cadastros.listaconvidados",
                        verbose_name="Lista",
                    ),
                ),
            ],
            options={
                "verbose_name": "Convidado",
                "verbose_name_plural": "Convidados",
                "unique_together": {("lista", "cpf")},
            },
        ),
    ]
