# Generated by Django 4.2.10 on 2025-10-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="condominio",
            name="is_ativo",
            field=models.BooleanField(
                default=True,
                help_text="Indica se o condomínio está ativo",
                verbose_name="Ativo",
            ),
        ),
    ]
