# Generated by Django 4.2.10 on 2025-10-10 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cadastros", "0002_condominio_is_ativo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="encomenda",
            name="destinatario",
        ),
        migrations.AddField(
            model_name="encomenda",
            name="destinatario_nome",
            field=models.CharField(
                blank=True,
                help_text="Nome da pessoa que receberá a encomenda",
                max_length=255,
                null=True,
                verbose_name="Nome do Destinatário",
            ),
        ),
        migrations.CreateModel(
            name="Unidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        help_text="Número ou identificação da unidade (ex: 101, 201A, etc.)",
                        max_length=20,
                        verbose_name="Número da Unidade",
                    ),
                ),
                (
                    "bloco",
                    models.CharField(
                        blank=True,
                        help_text="Bloco ou torre onde a unidade está localizada",
                        max_length=20,
                        null=True,
                        verbose_name="Bloco",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se a unidade está ativa no sistema",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unidades_criadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "morador",
                    models.ForeignKey(
                        blank=True,
                        help_text="Morador responsável pela unidade",
                        limit_choices_to={"groups__name": "Moradores"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unidades",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Morador",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unidades_atualizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidade",
                "verbose_name_plural": "Unidades",
                "ordering": ["bloco", "numero"],
            },
        ),
        migrations.AddField(
            model_name="encomenda",
            name="unidade",
            field=models.ForeignKey(
                blank=True,
                help_text="Unidade destinatária da encomenda",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="encomendas",
                to="cadastros.unidade",
                verbose_name="Unidade",
            ),
        ),
    ]
