# Generated by Django 4.2.10 on 2026-03-01 20:50 — replaced to fix wrong model

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cadastros", "0002_evento_imagem_db"),
    ]

    operations = [
        # Drop old tables if they exist from a previous wrong migration
        migrations.RunSQL(
            "DROP TABLE IF EXISTS cadastros_convidadolista;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS cadastros_listaconvidadosevento;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Create correct ListaConvidados model (no FK to Evento)
        migrations.CreateModel(
            name="ListaConvidados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=255, verbose_name="Título"),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True, default="", verbose_name="Descrição"
                    ),
                ),
                (
                    "data_evento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Evento"
                    ),
                ),
                (
                    "ativa",
                    models.BooleanField(default=True, verbose_name="Ativa"),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "morador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listas_convidados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Morador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lista de Convidados",
                "verbose_name_plural": "Listas de Convidados",
            },
        ),
        # Create ConvidadoLista model (FK to ListaConvidados)
        migrations.CreateModel(
            name="ConvidadoLista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf", models.CharField(max_length=11, verbose_name="CPF")),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="Nome"),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "lista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="convidados",
                        to="cadastros.listaconvidados",
                        verbose_name="Lista",
                    ),
                ),
            ],
            options={
                "verbose_name": "Convidado",
                "verbose_name_plural": "Convidados",
                "unique_together": {("lista", "cpf")},
            },
        ),
    ]
