# Generated by Django 4.2.10 on 2026-03-01 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cadastros", "0003_lista_convidados"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ocorrencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("problema", "Problema"), ("sugestao", "Sugestão")],
                        max_length=10,
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberta", "Aberta"),
                            ("em_andamento", "Em Andamento"),
                            ("resolvida", "Resolvida"),
                            ("fechada", "Fechada"),
                        ],
                        default="aberta",
                        max_length=20,
                    ),
                ),
                ("resposta", models.TextField(blank=True, null=True)),
                ("respondido_em", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocorrencias_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "respondido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ocorrencias_respondidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ocorrência",
                "verbose_name_plural": "Ocorrências",
                "ordering": ["-created_at"],
            },
        ),
    ]
