# Generated by Django 4.2.10 on 2025-10-10 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cadastros", "0003_remove_encomenda_destinatario_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unidade",
            name="morador",
            field=models.ForeignKey(
                blank=True,
                help_text="Morador responsável pela unidade",
                limit_choices_to=models.Q(
                    ("groups__name__iexact", "Moradores"),
                    ("groups__name__iexact", "Síndicos"),
                    ("groups__name__iexact", "Sindicos"),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unidades",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Morador",
            ),
        ),
    ]
