# Generated by Django 4.2.10 on 2026-03-02 22:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0004_add_ocorrencia_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="convidadolista",
            name="email",
            field=models.EmailField(
                blank=True,
                default="",
                max_length=254,
                verbose_name="E-mail do Convidado",
            ),
        ),
        migrations.AddField(
            model_name="convidadolista",
            name="entrada_confirmada",
            field=models.BooleanField(default=False, verbose_name="Entrada Confirmada"),
        ),
        migrations.AddField(
            model_name="convidadolista",
            name="entrada_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data/Hora da Entrada"
            ),
        ),
        migrations.AddField(
            model_name="convidadolista",
            name="qr_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Token QR Code",
            ),
        ),
        migrations.AddField(
            model_name="listaconvidados",
            name="espaco",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listas_convidados",
                to="cadastros.espaco",
                verbose_name="Espaço do Evento",
            ),
        ),
        migrations.AddField(
            model_name="listaconvidados",
            name="local_tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("espaco", "Espaço do Condomínio"),
                    ("unidade", "Unidade do Morador"),
                ],
                default="",
                max_length=10,
                verbose_name="Tipo de Local do Evento",
            ),
        ),
        migrations.AddField(
            model_name="listaconvidados",
            name="unidade_evento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listas_convidados_evento",
                to="cadastros.unidade",
                verbose_name="Unidade do Evento",
            ),
        ),
    ]
