# Generated by Django 4.2.10 on 2025-10-10 13:44

import cadastros.models.veiculo
import cadastros.models.visitante
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cadastros", "0004_alter_unidade_morador"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitante",
            name="placa_veiculo",
            field=models.CharField(
                blank=True,
                help_text="Placa do veículo do visitante (opcional, formato ABC-1234 ou ABC1D23)",
                max_length=8,
                null=True,
                validators=[cadastros.models.visitante.validate_placa_brasileira],
                verbose_name="Placa do Veículo",
            ),
        ),
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "placa",
                    models.CharField(
                        help_text="Placa do veículo (formato ABC-1234 ou ABC1D23)",
                        max_length=8,
                        validators=[cadastros.models.veiculo.validate_placa_brasileira],
                        verbose_name="Placa",
                    ),
                ),
                (
                    "marca_modelo",
                    models.CharField(
                        help_text="Marca e modelo do veículo (ex: Toyota Corolla)",
                        max_length=100,
                        verbose_name="Marca e Modelo",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o veículo está ativo no sistema",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="veiculos_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "morador",
                    models.ForeignKey(
                        help_text="Morador proprietário do veículo",
                        limit_choices_to=models.Q(
                            ("groups__name__iexact", "Moradores"),
                            ("groups__name__iexact", "Síndicos"),
                            ("groups__name__iexact", "Sindicos"),
                            _connector="OR",
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="veiculos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Morador",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="veiculos_atualizados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veículo",
                "verbose_name_plural": "Veículos",
                "ordering": ["-created_on"],
                "unique_together": {("placa", "morador")},
            },
        ),
    ]
