# Generated by Django 4.2.10 on 2026-03-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0005_lista_convidados_qrcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="condominio",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Logo do condomínio (png, jpg, jpeg, svg — qualquer tamanho)",
                null=True,
                upload_to="condominios/logos/",
            ),
        ),
    ]
