# Generated by Django 4.2.10 on 2026-04-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0006_convidadolistacerimonial_cpf_opcional"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="eventocerimonialconvite",
            name="unique_convite_ativo_por_evento_tipo",
        ),
        migrations.AddConstraint(
            model_name="eventocerimonialconvite",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ativo", True)),
                fields=("evento", "tipo", "ativo"),
                name="unique_convite_ativo_por_evento_tipo",
            ),
        ),
    ]
