# Generated by Django 4.2.10 on 2026-03-13 23:52

import django.db.models.deletion
from django.db import migrations, models


def forwards_copy_grupo_to_grupos(apps, schema_editor):
    Aviso = apps.get_model("cadastros", "Aviso")
    for aviso in Aviso.objects.exclude(grupo__isnull=True).iterator():
        aviso.grupos.add(aviso.grupo_id)


def backwards_copy_grupos_to_grupo(apps, schema_editor):
    Aviso = apps.get_model("cadastros", "Aviso")
    for aviso in Aviso.objects.filter(grupo__isnull=True).iterator():
        first_group_id = aviso.grupos.values_list("id", flat=True).first()
        if first_group_id:
            aviso.grupo_id = first_group_id
            aviso.save(update_fields=["grupo"])


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("cadastros", "0006_remove_logo_validator_condominio"),
    ]

    operations = [
        migrations.AddField(
            model_name="aviso",
            name="grupos",
            field=models.ManyToManyField(
                blank=True,
                help_text="Grupos de usuários que verão este aviso",
                related_name="avisos_destino",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="aviso",
            name="grupo",
            field=models.ForeignKey(
                blank=True,
                help_text="(Legado) grupo principal de usuários que verá este aviso",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avisos",
                to="auth.group",
            ),
        ),
        migrations.RunPython(
            forwards_copy_grupo_to_grupos,
            backwards_copy_grupos_to_grupo,
        ),
    ]
