# Generated by Django 4.2.10 on 2025-10-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0007_espaco_espacoreserva_espacoinventarioitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="espacoreserva",
            options={
                "ordering": ["-data_reserva"],
                "verbose_name": "Reserva de Espaço",
                "verbose_name_plural": "Reservas de Espaço",
            },
        ),
        migrations.AddField(
            model_name="espaco",
            name="valor_aluguel",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Valor cobrado pela reserva do espaço por dia",
                max_digits=10,
                verbose_name="Valor do Aluguel",
            ),
        ),
        migrations.AddField(
            model_name="espacoreserva",
            name="data_reserva",
            field=models.DateField(
                default="2025-10-10",
                help_text="Data do dia reservado (dia completo)",
                verbose_name="Data da Reserva",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="espacoreserva",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("confirmada", "Confirmada"),
                    ("cancelada", "Cancelada"),
                ],
                default="confirmada",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="espacoreserva",
            name="valor_cobrado",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Valor que será cobrado pela reserva",
                max_digits=10,
                verbose_name="Valor Cobrado",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="espacoreserva",
            unique_together={("espaco", "data_reserva")},
        ),
        migrations.RemoveField(
            model_name="espacoreserva",
            name="data_hora",
        ),
    ]
