# Generated by Django 4.2.10 on 2025-10-10 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cadastros", "0008_alter_espacoreserva_options_espaco_valor_aluguel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Título do evento",
                        max_length=255,
                        verbose_name="Título",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        help_text="Descrição detalhada do evento",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "local_texto",
                    models.CharField(
                        blank=True,
                        help_text="Descrição do local quando não for um espaço cadastrado",
                        max_length=255,
                        null=True,
                        verbose_name="Local (texto)",
                    ),
                ),
                (
                    "data_evento",
                    models.DateField(
                        help_text="Data em que o evento acontecerá",
                        verbose_name="Data do Evento",
                    ),
                ),
                (
                    "hora_inicio",
                    models.TimeField(
                        help_text="Hora de início do evento",
                        verbose_name="Hora de Início",
                    ),
                ),
                (
                    "hora_fim",
                    models.TimeField(
                        help_text="Hora de término do evento",
                        verbose_name="Hora de Término",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        help_text="Imagem ilustrativa do evento",
                        null=True,
                        upload_to="eventos/",
                        verbose_name="Imagem",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "espaco",
                    models.ForeignKey(
                        blank=True,
                        help_text="Espaço onde o evento acontecerá (opcional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos",
                        to="cadastros.espaco",
                        verbose_name="Espaço",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_atualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "ordering": ["data_evento", "hora_inicio"],
            },
        ),
    ]
