# Generated by Django 4.2 on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0011_encomenda_contestacao_resposta_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="condominio",
            name="signup_slug",
            field=models.SlugField(
                blank=True,
                help_text="Slug único usado no link de cadastro de moradores",
                max_length=120,
                null=True,
                unique=True,
                verbose_name="Slug de cadastro",
            ),
        ),
        migrations.AddField(
            model_name="condominio",
            name="signup_token",
            field=models.CharField(
                blank=True,
                help_text="Token secreto para validar o link de cadastro de moradores",
                max_length=64,
                null=True,
                verbose_name="Token de cadastro",
            ),
        ),
    ]
