# Generated by Django 4.2.10 on 2025-10-13 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0011_evento_old_fields_nullable"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evento",
            options={"verbose_name": "Evento", "verbose_name_plural": "Eventos"},
        ),
        migrations.RemoveField(
            model_name="evento",
            name="data_evento",
        ),
        migrations.RemoveField(
            model_name="evento",
            name="hora_fim",
        ),
        migrations.RemoveField(
            model_name="evento",
            name="hora_inicio",
        ),
        migrations.RemoveField(
            model_name="unidade",
            name="morador",
        ),
    ]
