# Generated by Django 4.2.10 on 2025-10-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0012_alter_evento_options_remove_evento_data_evento_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="condominio",
            name="endereco",
        ),
        migrations.AddField(
            model_name="condominio",
            name="cep",
            field=models.CharField(
                blank=True,
                default="",
                help_text="CEP do condomínio (somente números)",
                max_length=8,
                verbose_name="CEP",
            ),
        ),
        migrations.AddField(
            model_name="condominio",
            name="complemento",
            field=models.CharField(
                blank=True,
                help_text="Complemento do endereço (opcional)",
                max_length=100,
                null=True,
                verbose_name="Complemento",
            ),
        ),
        migrations.AddField(
            model_name="condominio",
            name="numero",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Número do endereço",
                max_length=10,
                verbose_name="Número",
            ),
        ),
    ]
