# Generated by Django 4.2.10 on 2025-10-14 19:25

import app.utils.image_validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0014_alter_condominio_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="condominio",
            name="logo_db_content_type",
            field=models.CharField(
                blank=True,
                help_text="Content-Type do arquivo",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="condominio",
            name="logo_db_data",
            field=models.BinaryField(
                blank=True,
                help_text="Dados binários da logo (se armazenada no DB)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="condominio",
            name="logo_db_filename",
            field=models.CharField(
                blank=True,
                help_text="Nome original do arquivo",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="condominio",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Logo quadrada até 250x250px (png, jpg, jpeg, svg)",
                null=True,
                upload_to="condominios/logos/",
                validators=[app.utils.image_validators.validate_logo_file],
            ),
        ),
    ]
