# Generated by Django 4.2.10 on 2026-03-31 22:24

import app.utils.validators
import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "Este nome de usuário já está em uso."
                        },
                        max_length=150,
                        unique=True,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "cpf",
                    models.CharField(
                        help_text="CPF no formato XXX.XXX.XXX-XX ou apenas números",
                        max_length=14,
                        unique=True,
                        validators=[app.utils.validators.validate_cpf],
                        verbose_name="CPF",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Telefone no formato (XX) XXXXX-XXXX ou apenas números",
                        max_length=15,
                        validators=[app.utils.validators.validate_phone],
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "first_access",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o usuário ainda não alterou a senha padrão",
                        verbose_name="Primeiro Acesso",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "foto_db_data",
                    models.BinaryField(
                        blank=True,
                        help_text="Foto de perfil do usuário armazenada em BLOB",
                        null=True,
                    ),
                ),
                (
                    "foto_db_content_type",
                    models.CharField(
                        blank=True,
                        help_text="Content-Type da foto de perfil",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "foto_db_filename",
                    models.CharField(
                        blank=True,
                        help_text="Nome do arquivo da foto de perfil",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
                "ordering": ["full_name"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
