# Generated by Django 4.2.10 on 2025-10-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_access",
            field=models.BooleanField(
                default=True,
                help_text="Indica se o usuário ainda não alterou a senha padrão",
                verbose_name="Primeiro Acesso",
            ),
        ),
    ]
