# Generated by Django 4.2.10 on 2025-10-09 19:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0002_user_first_access"),
    ]

    operations = []
