# Generated by Django 4.2.10 on 2025-10-09 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0001_initial"),
        ("access", "0003_auto_20251009_1953"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="condominio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios",
                to="cadastros.condominio",
                verbose_name="Condomínio",
            ),
        ),
    ]
