# Generated by Django 4.2 on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0003_user_unidades_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="foto_db_content_type",
            field=models.CharField(
                blank=True,
                help_text="Content-Type da foto de perfil",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="foto_db_data",
            field=models.BinaryField(
                blank=True,
                help_text="Foto de perfil do usuário armazenada em BLOB",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="foto_db_filename",
            field=models.CharField(
                blank=True,
                help_text="Nome do arquivo da foto de perfil",
                max_length=255,
                null=True,
            ),
        ),
    ]
