# Generated by Django 4.2.10 on 2025-10-13 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0012_alter_evento_options_remove_evento_data_evento_and_more"),
        ("access", "0004_user_condominio"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="unidade",
            field=models.OneToOneField(
                blank=True,
                help_text="Unidade onde o morador reside",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="morador",
                to="cadastros.unidade",
                verbose_name="Unidade",
            ),
        ),
    ]
